version: '3.7'
services: 
 server:
  build: 
    context: .
    dockerfile: DockerFile
  ports: 
    - 3000:3000
  restart: always
  depends_on: 
    - db
 db:
  image: redis
  restart: always
  ports: 
    - 6379:6379